adminasiu/asiu_app/asiu_admin/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # url(r'^$', views.base, name='base'),
    url(r'^$', views.authentication, name='login'),
    url(r'^programador$', views.programador, name='programador'),
    url(r'^administrador$', views.administrador, name='administrador'),
    url(r'^perfil$', views.perfil, name='perfil'),
    url(r'^administrador/predios/activos$', views.predios_activos, name='predios_activos'),
    url(r'^logout$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

adminasiu/asiu_app/asiu_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'asiu_admin'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('asiu_admin.urls', namespace='asiu_admin')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminasiu/asiu_app/templates/perfil_admin.html
{% extends "administrador.html" %}

{% load staticfiles %}

{% block content %}
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Perfil
      <small>{{ user.username }}</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="{% url "asiu_admin:administrador" %}"><i class="fa fa-dashboard"></i> Inicio</a></li>
      <li>Perfil</li>
    </ol>
  </section>


  <section class="content">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Perfil</h3>
      </div><!-- /.box-header -->

      <div class="box-body">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
       
       
              <div class="panel panel-info">
                <div class="panel-heading">
                  <h3 class="panel-title">{{ user.first_name }} {{ user.last_name }}</h3>
                </div>
                <div class="panel-body">
                  <div class="row">
                    <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="{{ user.avatar.url }}" class="img-circle img-responsive"> </div>
                    
                    <!--<div class="col-xs-10 col-sm-10 hidden-md hidden-lg"> <br>
                      <dl>
                        <dt>DEPARTMENT:</dt>
                        <dd>Administrator</dd>
                        <dt>HIRE DATE</dt>
                        <dd>11/12/2013</dd>
                        <dt>DATE OF BIRTH</dt>
                           <dd>11/12/2013</dd>
                        <dt>GENDER</dt>
                        <dd>Male</dd>
                      </dl>
                    </div>-->
                    <div class=" col-md-9 col-lg-9 "> 
                      <table class="table table-user-information">
                        <tbody>
                          <tr>
                            <td>Nombre de Usuario:</td>
                            <td>{{ user.username }}</td>
                          </tr>

                          <tr>
                            <td>Nombres:</td>
                            <td>{{ user.first_name }}</td>
                          </tr>

                          <tr>
                            <td>Apellidos:</td>
                            <td>{{ user.last_name }}</td>
                          </tr>

                          <tr>
                            <td>Tipo:</td>
                            <td>{{ user.tipo }}</td>
                          </tr>

                          <tr>
                            <td>Email</td>
                            <td><a href="mailto:{{ user.email }}">{{ user.email }}</a></td>
                          </tr>

                          <tr>
                            <td>Miembro desde</td>
                            <td>{{ user.date_joined }}</td>
                          </tr>
                        </tbody>
                      </table>
                      
                      <!-- <a href="#" class="btn btn-primary">My Sales Performance</a>
                      <a href="#" class="btn btn-primary">Team Sales Performance</a> -->
                    </div>
                  </div>
                </div>

                <div class="panel-footer">
                  <a class="btn btn-social-icon btn-twitter"><i class="fa fa-edit"></i></a>
                </div>
                
              </div>
            </div>
          </div>
        </div>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </section>
{% endblock %}

adminasiu/asiu_app/templates/predios_activos.html
{% extends "administrador.html" %}

{% load staticfiles %}

{% block content %}
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Predios
      <small>Activos</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="{% url "asiu_admin:administrador" %}"><i class="fa fa-dashboard"></i> Inicio</a></li>
      <li class="active">Predios</li>
      <li>Activos</li>
    </ol>
  </section>


  <section class="content">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Predios Activos</h3>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>Matrícula</th>
              <th>Nombres</th>
              <th>Apellidos</th>
              <th>Dirección</th>
              <th>Teléfono</th>
              <th>Celular</th>
              <th>Ciudad</th>
              <th>Fotografía</th>
            </tr>
          </thead>

          <tbody>
            {% for base in bases %}
              <tr>
                <td>{{ base.matricula }}</td>
                <td>{{ base.nombres }}</td>
                <td>{{ base.apellidos }}</td>
                <td>{{ base.direccion1 }}</td>
                <td>{{ base.telefono }}</td>
                <td>{{ base.celular }}</td>
                <td>{{ base.ciudad }}</td>
                <td><img src="{{ base.fotografia_del_predio.url }}" width="50px"></td>
              </tr>
            {% endfor %}
          </tbody>
          <!-- <tfoot>
            <tr>
              <th>Matrícula</th>
              <th>Nombres</th>
              <th>Apellidos</th>
              <th>Dirección</th>
              <th>Teléfono</th>
              <th>Celular</th>
              <th>Ciudad</th>
              <th>Fotografía</th>
            </tr>
          </tfoot> -->
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </section>
{% endblock %}